export interface IHoSoBenhAn {
  ID: string;
  MaBANoiTru?: string | null;
  SoBenhAn?: string | null;
  MaBN?: string | null;
  Hoten?: string | null;
  Ngaysinh?: string | null;
  Gioitinh?: string | null;
  Dienthoai?: string | null;
  Diachi?: string | null;
  SoCCCD?: string | null;
  SoNhapVien?: string | null;
  SoVaoVien?: string | null;
  SoLuuTru?: string | null;
  KhoaVaoVien?: string | null;
  KhoaDieuTri?: string | null;
  TenKhoaDieuTri?: string | null;
  NgayVao?: Date | string | null;
  NgayRa?: Date | string | null;
  LoaiBenhAn?: string | null;
  NoiDungJson?: string | null;
  NoiDungXml?: string | null;
  NoiDungPdf?: string | null;
  TruongKhoaKyTen?: string | null;
  GdbvKyTen?: string | null;
  BsLamBAKyTen?: string | null;
  BsDieuTriKyTen?: string | null;
  TrangThaiBA?: string | null;
  NgayCapNhat?: string | null;
  NgayTao?: string | null;
  ViTriLuuTru?: string | null;
  LoaiLuuTru?: string | null;
  NgayLuuTru?: Date | null;
  TenLoaiLuuTru?: string | null;
  SoNamLuuTru?: string | null;
  TrangThaiKetXuat?: string | null;
  NgayKetXuat?: string | null;
  NguoiKetXuat?: string | null;
}
