"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Box } from "@mui/material";
import SideMenu from "@/components/SideMenu";
import AppNavbar from "@/components/AppNavbar";
import AppBarTop from "@/components/AppBarTop";
import { useEffect } from "react";
import { getMenuItems } from "@/actions/menu"; 
import { useMenuStore } from "@/store/menu";
import { useUserStore } from "@/store/user";
import { LocalizationProvider } from "@mui/x-date-pickers";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { usePathname } from "next/navigation";
import { getClaimsFromToken } from "@/utils/auth"; // Assuming you have a utility function to decode JWT  

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const pathnameNotUseLayout = ["/login"];
  const useNoLayout = pathnameNotUseLayout.some((path) =>
    pathname.startsWith(path)
  );
  const { setData } = useMenuStore();
  const {setUserData} = useUserStore(); 
  useEffect(() => {
    InitData();
  }, []);

  const InitData = async () => {
    try {
      const menu = await getMenuItems();
      //console.log("Menu items fetched:", menu);
      setData(menu);

      const claims = getClaimsFromToken();
      if (claims) {
        setUserData(claims);
        // Log or handle the claims as needed 
        //console.log("User claims:", claims);
        // You can set user claims in a global state or context if needed
      } else {
        console.warn("No valid claims found in token");
      } 
    } catch (error) {
      console.error("Error initializing data:", error);
    }
  };
  if (useNoLayout) {
    return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Box className="flex w-screen h-screen">
            <Box className="bg-blue-100 h-full w-full">{children}</Box>
          </Box>
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LocalizationProvider dateAdapter={AdapterDayjs}>
          <Box className="flex w-screen h-screen">
            <SideMenu />
            {/* <AppNavbar /> */}
            <Box className="w-full h-full flex flex-col flex-1 overflow-hidden">
              <AppBarTop />
              <Box className="bg-blue-100 h-full w-full">{children}</Box>
            </Box>
          </Box>
        </LocalizationProvider>
      </body>
    </html>
  );
}
