"use client";
import { getMenuItems } from "@/actions/menu";
import AppBarTop from "@/components/AppBarTop";
import SideMenu from "@/components/SideMenu";
import { useMenuStore } from "@/store/menu";
import { useUserStore } from "@/store/user";
import { getClaimsFromToken } from "@/utils/auth"; // Assuming you have a utility function to decode JWT
import { Box } from "@mui/material";
import { LocalizationProvider } from "@mui/x-date-pickers";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { Geist, Geist_Mono } from "next/font/google";
import { usePathname } from "next/navigation"; // Cho App Router (Next.js 13+)
import { useCallback, useEffect } from "react";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const pathnameNotUseLayout = ["/login"];
  const useNoLayout = pathnameNotUseLayout.some((path) =>
    pathname ? pathname.startsWith(path) : false
  );
  const { setData } = useMenuStore();
  const { setUserData } = useUserStore();

  const initMenu = useCallback(async () => {
    try {
      const menu = await getMenuItems();
      //console.log("Menu items fetched:", menu);
      setData(menu);
    } catch (error) {
      console.error("Error fetching menu items:", error);
    }
  }, [setData]);

  const initUser = useCallback(async () => {
    try {
      const claims = getClaimsFromToken();
      console.log("Claims fetched 1111111111111111111:", claims);
      if (claims) {
        setUserData(claims);
      } else {
        console.warn("No valid claims found in token");
      }
    } catch (error) {
      console.error("Error initializing user data:", error);
    }
  }, [setUserData]);

  useEffect(() => {
    initUser();
  }, [initUser]);

  useEffect(() => {
    initMenu();
  }, [initMenu]);

  if (useNoLayout) {
    return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Box className="flex w-screen h-screen">
            <Box className="bg-blue-100 h-full w-full">{children}</Box>
          </Box>
          <Toaster />
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LocalizationProvider dateAdapter={AdapterDayjs}>
          <Box className="flex w-screen h-screen">
            <SideMenu />
            {/* <AppNavbar /> */}
            <Box className="w-full h-full flex flex-col flex-1 overflow-hidden">
              <AppBarTop />
              <Box className="bg-blue-100 h-full w-full overflow-hidden">
                {children}
              </Box>
            </Box>
          </Box>
          <Toaster />
        </LocalizationProvider>
      </body>
    </html>
  );
}
